server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/event_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

info:
  app:
    name: user-service
    description: A microservice responsible for managing users
    version: 1.0.0

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
      
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
